-- Verificar ENUMs existentes
SELECT typname FROM pg_type WHERE typtype = 'e';

-- Se os ENUMs não existirem, execute os comandos abaixo um por vez:

-- 1. Criar ENUMs (execute um por vez)
CREATE TYPE "UserRole" AS ENUM ('FUNCIONARIO', 'TECNICO', 'APROVADOR', 'GESTOR', 'ADMIN');

CREATE TYPE "ServiceOrderStatus" AS ENUM ('ABERTA', 'EM_ANALISE', 'AGUARDANDO_DESLOCAMENTO', 'EM_EXECUCAO', 'AGUARDANDO_MATERIAL', 'AGUARDANDO_ORCAMENTO', 'AGUARDANDO_APROVACAO', 'MATERIAL_APROVADO', 'FINALIZADA', 'CANCELADA');

CREATE TYPE "Priority" AS ENUM ('BAIXA', 'NORMAL', 'ALTA', 'URGENTE');

CREATE TYPE "ProblemCategory" AS ENUM ('HARDWARE', 'SOFTWARE', 'REDE', 'IMPRESSORA', 'TELEFONIA', 'SISTEMA', 'OUTROS');

CREATE TYPE "AttachmentType" AS ENUM ('IMAGE', 'DOCUMENT', 'VIDEO', 'OTHER');

CREATE TYPE "QuoteStatus" AS ENUM ('SOLICITADO', 'RECEBIDO', 'APROVADO', 'REJEITADO');

CREATE TYPE "NotificationType" AS ENUM ('NEW_OS', 'OS_UPDATED', 'OS_ASSIGNED', 'OS_COMPLETED', 'OS_CANCELLED', 'MATERIAL_NEEDED', 'URGENT', 'INFO');
